# Generated by Django 3.0.3 on 2020-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogtitle', models.CharField(max_length=200)),
                ('Blogdescription', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
